#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# create_fre_bundle_installer.sh
#
# Packages the existing abbyy_bundle/ into a self-extracting installer shell
# script (FRE_bundle.sh) that mimics the ABBYY FRE12.sh CLI interface.
#
# WHY: If you don't have the original FRE*.sh downloaded from ABBYY's portal,
# this creates an equivalent installer from the already-extracted bundle on disk.
# The resulting FRE_bundle.sh can be used with Dockerfile.installer exactly
# like the official FRE*.sh.
#
# WHAT IT CREATES:
#   FRE_bundle.sh  — self-extracting installer with same CLI as FRE12.sh
#
# CLI interface of the output FRE_bundle.sh:
#   FRE_bundle.sh -- [OPTIONS]
#   Options:
#     --install-dir DIR                Install FREngine12 to DIR
#     --service-address HOST           Use remote LicensingService (writes to XML)
#     --license-path FILE              Path to .ABBYY.ActivationToken
#     --license-password PASSWORD      Password for the token
#     --skip-local-service-installation  Do not set up systemd service
#     --skip-local-license-activation    Skip online license activation call
#     --developer-install              Copy CLI samples too
#
# HOW TO USE:
#   1. Create the bundle installer:
#        bash scripts/create_fre_bundle_installer.sh
#
#   2. Place FRE_bundle.sh in the Docker build context (same dir as Dockerfile.installer)
#      Then uncomment Option 1 in Dockerfile.installer and comment out Option 2.
#
#   3. Build:
#        docker build -f Dockerfile.installer \
#          --build-arg SERVICE_ADDRESS=sgml-abbyy-ls.default.svc.cluster.local \
#          -t sgml-pipeline-prod:0.0.22-installer .
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUNDLE_DIR="$REPO_DIR/abbyy_bundle"
OUTPUT="$REPO_DIR/FRE_bundle.sh"

echo "========================================"
echo "  ABBYY FRE12 Bundle Installer Creator"
echo "========================================"
echo ""

# ── Validate bundle ───────────────────────────────────────────────────────────
if [ ! -d "$BUNDLE_DIR/FREngine12/Bin" ]; then
    echo "ERROR: abbyy_bundle/FREngine12/Bin not found"
    echo "       Run: bash scripts/bundle_abbyy.sh  to create the bundle first"
    exit 1
fi

if [ ! -f "$BUNDLE_DIR/LicensingService" ]; then
    echo "ERROR: abbyy_bundle/LicensingService not found"
    exit 1
fi

echo "[1/3] Packing abbyy_bundle/ into tarball..."
TARBALL="/tmp/fre_bundle_payload.tar.gz"

# Pack everything needed: FREngine12, LicensingService, libs, licenses
tar -czf "$TARBALL" \
    -C "$BUNDLE_DIR" \
    FREngine12 \
    LicensingService \
    usr_local_lib_abbyy \
    var_lib_abbyy

TARBALL_SIZE=$(du -sh "$TARBALL" | cut -f1)
echo "    Tarball: $TARBALL ($TARBALL_SIZE)"

# ── Base64-encode the tarball ──────────────────────────────────────────────────
echo "[2/3] Encoding tarball..."
PAYLOAD_B64=$(base64 -w 0 "$TARBALL")

# ── Write self-extracting installer ───────────────────────────────────────────
echo "[3/3] Writing $OUTPUT ..."

cat > "$OUTPUT" << 'INSTALLER_HEADER'
#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# FRE_bundle.sh — Self-extracting ABBYY FREngine12 installer
# Generated by: scripts/create_fre_bundle_installer.sh
# Compatible CLI interface with official ABBYY FRE12.sh installer.
# ─────────────────────────────────────────────────────────────────────────────

INSTALL_DIR="/opt/ABBYY/FREngine12"
SERVICE_ADDRESS=""
LICENSE_PATH=""
LICENSE_PASSWORD=""
SKIP_LS_INSTALL=0
SKIP_LICENSE_ACTIVATION=0
DEVELOPER_INSTALL=0

usage() {
    cat <<EOF
Usage: $0 -- [OPTIONS]
Options:
  --install-dir DIR                  FREngine12 install directory (default: /opt/ABBYY/FREngine12)
  --service-address HOST             External LicensingService address (host or host:port)
  --license-path FILE                Path to .ABBYY.ActivationToken
  --license-password PASSWORD        License token password
  --skip-local-service-installation  Do not install LicensingService as a system service
  --skip-local-license-activation    Skip online license activation
  --developer-install                Install developer samples
  -h, --help                         Show this help
EOF
}

# Parse arguments (skip the leading "--")
shift_done=0
for arg in "$@"; do
    if [ "$shift_done" = "0" ] && [ "$arg" = "--" ]; then
        shift_done=1
        continue
    fi
    [ "$shift_done" = "0" ] && continue
    break
done

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --install-dir)              INSTALL_DIR="$2";       shift 2;;
            --service-address)          SERVICE_ADDRESS="$2";   shift 2;;
            --license-path)             LICENSE_PATH="$2";      shift 2;;
            --license-password)         LICENSE_PASSWORD="$2";  shift 2;;
            --skip-local-service-installation) SKIP_LS_INSTALL=1; shift;;
            --skip-local-license-activation)   SKIP_LICENSE_ACTIVATION=1; shift;;
            --developer-install)        DEVELOPER_INSTALL=1;    shift;;
            -h|--help)                  usage; exit 0;;
            --) shift;;
            *) echo "Unknown option: $1"; usage; exit 1;;
        esac
    done
}

# Find where "--" separator is and parse after it
ARGS=("$@")
FOUND_SEP=0
PASS_ARGS=()
for arg in "${ARGS[@]}"; do
    if [ "$FOUND_SEP" = "1" ]; then
        PASS_ARGS+=("$arg")
    elif [ "$arg" = "--" ]; then
        FOUND_SEP=1
    fi
done

parse_args "${PASS_ARGS[@]+"${PASS_ARGS[@]}"}"

echo "[FRE_bundle] Extracting ABBYY FineReader Engine 12..."
echo "[FRE_bundle] Install directory: $INSTALL_DIR"

# Extract embedded tarball
TMPDIR_EXTRACT=$(mktemp -d)
trap "rm -rf $TMPDIR_EXTRACT" EXIT

SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
PAYLOAD_LINE=$(grep -n "^PAYLOAD_BASE64=" "$SELF" | head -1 | cut -d: -f1)
PAYLOAD=$(sed -n "${PAYLOAD_LINE}p" "$SELF" | sed 's/^PAYLOAD_BASE64=//')

echo "$PAYLOAD" | base64 -d | tar -xzf - -C "$TMPDIR_EXTRACT"

# ── Install FREngine12 ─────────────────────────────────────────────────────────
mkdir -p "$INSTALL_DIR"
echo "[FRE_bundle] Installing FREngine12 → $INSTALL_DIR"
cp -a "$TMPDIR_EXTRACT/FREngine12/." "$INSTALL_DIR/"
chmod +x \
    "$INSTALL_DIR/Samples/CommandLineInterface/CommandLineInterface" \
    "$INSTALL_DIR/Bin/FREngineProcessor" \
    "$INSTALL_DIR/Bin/LicenseManager.Console" 2>/dev/null || true
find "$INSTALL_DIR" -name "*.sh" -exec chmod +x {} \; 2>/dev/null || true
rm -f "$INSTALL_DIR/Bin/libProtection.Developer.so" 2>/dev/null || true

# ── Install LicensingService ───────────────────────────────────────────────────
mkdir -p /usr/local/bin/ABBYY/SDK/12/Licensing
mkdir -p /usr/local/lib/ABBYY/SDK/12/Licensing
mkdir -p /var/lib/ABBYY/SDK/12/Licenses

echo "[FRE_bundle] Installing LicensingService"
cp "$TMPDIR_EXTRACT/LicensingService" /usr/local/bin/ABBYY/SDK/12/Licensing/LicensingService
chmod +x /usr/local/bin/ABBYY/SDK/12/Licensing/LicensingService

echo "[FRE_bundle] Installing LicensingService libraries"
cp -a "$TMPDIR_EXTRACT/usr_local_lib_abbyy/." /usr/local/lib/ABBYY/

echo "[FRE_bundle] Installing license files"
cp -a "$TMPDIR_EXTRACT/var_lib_abbyy/ABBYY/." /var/lib/ABBYY/
chmod -R 777 /var/lib/ABBYY/

# ── Configure LicensingSettings.xml via activatefre.sh ───────────────────────
echo "[FRE_bundle] Configuring LicensingSettings.xml..."

ACTIVATE="$INSTALL_DIR/activatefre.sh"
if [ -x "$ACTIVATE" ]; then
    export RootScriptLaunched=1

    ACTIVATE_ARGS=(-- --install-dir "$INSTALL_DIR" --skip-local-service-installation)

    if [ -n "$SERVICE_ADDRESS" ]; then
        echo "[FRE_bundle] Using remote LicensingService: $SERVICE_ADDRESS"
        ACTIVATE_ARGS+=(--service-address "$SERVICE_ADDRESS" --skip-local-license-activation)
    elif [ -n "$LICENSE_PATH" ] && [ -n "$LICENSE_PASSWORD" ]; then
        echo "[FRE_bundle] Configuring online license: $LICENSE_PATH"
        ACTIVATE_ARGS+=(--license-path "$LICENSE_PATH" --license-password "$LICENSE_PASSWORD")
    else
        echo "[FRE_bundle] No SERVICE_ADDRESS or license credentials — using localhost"
        ACTIVATE_ARGS+=(--skip-local-license-activation)
    fi

    "$ACTIVATE" "${ACTIVATE_ARGS[@]}"
else
    # Fallback: write LicensingSettings.xml manually
    echo "[FRE_bundle] activatefre.sh not found — writing LicensingSettings.xml manually"
    SERVER="${SERVICE_ADDRESS:-127.0.0.1}"
    XML="<?xml version=\"1.0\" encoding=\"utf-8\"?>
<LicensingSettings>
<LocalLicenseServer>
        <ConnectionProtocol ProtocolType=\"Sockets\"/>
</LocalLicenseServer>
<LicensingServers>
        <MainNetworkLicenseServer ProtocolType=\"Sockets\" ServerAddress=\"${SERVER}\"/>
</LicensingServers>
</LicensingSettings>"
    echo "$XML" > "$INSTALL_DIR/Bin/LicensingSettings.xml"
    mkdir -p "$INSTALL_DIR/CommonBin/Licensing"
    echo "$XML" > "$INSTALL_DIR/CommonBin/Licensing/LicensingSettings.xml"
fi

# Show result
echo "[FRE_bundle] === Resulting LicensingSettings.xml ==="
cat "$INSTALL_DIR/Bin/LicensingSettings.xml"
echo ""
echo "[FRE_bundle] ✓ Installation complete"
echo "[FRE_bundle] Install dir : $INSTALL_DIR"
echo "[FRE_bundle] LS binary   : /usr/local/bin/ABBYY/SDK/12/Licensing/LicensingService"
echo "[FRE_bundle] License dir : /var/lib/ABBYY/SDK/12/Licenses/"
INSTALLER_HEADER

# Append the base64 payload
echo "PAYLOAD_BASE64=${PAYLOAD_B64}" >> "$OUTPUT"

chmod +x "$OUTPUT"

OUTPUT_SIZE=$(du -sh "$OUTPUT" | cut -f1)
rm -f "$TARBALL"

echo ""
echo "========================================"
echo " SUCCESS"
echo " Output: $OUTPUT ($OUTPUT_SIZE)"
echo ""
echo " Usage with Dockerfile.installer:"
echo "   Place FRE_bundle.sh in /home/securities_outsourcing/"
echo "   In Dockerfile.installer: uncomment Option 1 lines, comment Option 2"
echo ""
echo " Build (Mode A — fixed LS address baked in):"
echo "   docker build -f Dockerfile.installer \\"
echo "     --build-arg SERVICE_ADDRESS=sgml-abbyy-ls.default.svc.cluster.local \\"
echo "     -t sgml-pipeline-prod:0.0.22-installer ."
echo ""
echo " Build (Mode B — runtime ABBYY_LS_HOST):"
echo "   docker build -f Dockerfile.installer \\"
echo "     -t sgml-pipeline-prod:0.0.22-installer ."
echo "========================================"
